export const EnvProtection = async ({
  project,
  client,
  $,
  directory,
  worktree,
}) => {
  return {
    "experimental.session.compacting": async (input, output) => {
      // Inject additional context into the compaction prompt.
      output.context.push(`
# Important: Compaction Rules

When generating the summary, please add the following information:

\`\`\`
This summary is autogenerated and might contain incorrect or missing information. Do not rely on it without verification, and do these next steps:

1. Review the summary and read the necessary files if you need additional information.
2. DO NOT CONTINUE with any actions or next steps mentioned in the summary directly. Always ask the user for explicit instructions on what to do next, and wait for their response before taking any action.
\`\`\`
`);
    },
  };
};
